routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UserProfilesController@register');
Route::get('thanks', 'UserProfilesController@thanks');
Route::get('/signup', 'UserProfilesController@signup');
Route::get('/terms', 'UserProfilesController@terms');
Route::get('/getCount', 'UserProfilesController@getCount');
Route::post('/create', 'UserProfilesController@create');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');



Route::post('/pay', [
    'uses' => 'PaymentController@redirectToGateway',
    'as' => 'pay'
]);
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');
Route::get('/payment/webhook', 'PaymentController@handleGatewayWebhook');
Route::get('userProfiles/unpaid', 'UserProfilesController@unpaid');
Route::get('userProfiles/download_images', 'UserProfilesController@download_images');
Route::resource('userProfiles', 'UserProfilesController');

Route::resource('payments', 'PaymentController');


Route::resource('modelSettings', 'ModelSettingsController');

Route::resource('settings', 'SettingsController');

app/Models/UserProfiles.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Glorand\Model\Settings\Traits\HasSettingsTable;

/**
 * Class UserProfiles
 * @package App\Models
 * @version January 27, 2020, 5:15 pm UTC
 *
 * @property string title
 * @property string first_name
 * @property string other_name
 * @property string last_name
 * @property string sex
 * @property string dob
 * @property string marital_status
 * @property string profession
 * @property string employer
 * @property string home_address
 * @property string office_address
 * @property string email
 * @property string phone
 */
class UserProfiles extends Model implements HasMedia
{
    use SoftDeletes;
    use HasMediaTrait;
    use HasSettingsTable;

    public $table = 'user_profiles';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'title',
        'reference',
        'first_name',
        'other_name',
        'last_name',
        'sex',
        'dob',
        'marital_status',
        'profession',
        'employer',
        'home_address',
        'office_address',
        'email',
        'next_of_kin',
        'next_of_kin_phone',
        'phone'
    ];



    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'title' => 'string',
        'first_name' => 'string',
        'other_name' => 'string',
        'last_name' => 'string',
        'sex' => 'string',
        'dob' => 'string',
        'marital_status' => 'string',
        'profession' => 'string',
        'employer' => 'string',
        'home_address' => 'string',
        'office_address' => 'string',
        'email' => 'string',
        'next_of_kin' => 'string',
        'next_of_kin_phone' => 'string',
        'phone' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'title' => 'required',
        'first_name' => 'required',
        'last_name' => 'required',
        'sex' => 'required',
        //'dob' => 'required|date|date_format:d-m-Y',
        'marital_status' => 'required',
        'profession' => 'required',
        'employer' => 'required',
        'home_address' => 'required',
        'office_address' => 'required',
        'email' => 'required|email',
        'next_of_kin' => 'required',
        'next_of_kin_phone' => 'required',
        //'phone' => 'required|unique:user_profiles,phone',
        'phone' => 'required',
        'passport' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048'
    ];

    protected $appends = ['full_name'];

    public function getFullNameAttribute(){
        return $this->attributes['first_name']." ".$this->attributes['last_name'];
    }
    public function getTable()
    {
        return $this->table;
    }

    public function payments()
    {
        return $this->hasOne(Payment::class, 'profile_id')->orderByDesc('created_at');
    }

    function url_exists($url)
    {
        try {
            $headers = @get_headers($url);
            if ($headers && strpos($headers[0], '200')) {
                return true;
            } else {
                return false;
            }
        } catch (\Exception $exception) {
            return false;
        }
    }

    function getLogo($logo, $default = null)
    {
        if ($default == null) {
            $default = asset('img/default_product.png');
        }


        try {
            $res = $this->url_exists($logo);
        } catch (\Exception $exception) {
            $res = false;
        }
        if (!$res) {
            $logo = $default;
        }
        if (empty($logo)) {
            $logo = $default;
        }
        return $logo;
    }


    public function getUploadPhotoAttribute()
    {
        // dd(getLogo($this->attributes['upload_1_url']));
        return $this->getLogo($this->attributes['photo']);
    }

    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->width(368)
            ->height(232)
            ->sharpen(10);

        $this
            ->addMediaConversion('my-conversion')
            ->greyscale()
            ->withResponsiveImages();
    }

    public function registerMediaCollections()
    {
        $this
            ->addMediaCollection('passport')
            ->useFallbackUrl('/img/default_product.png')
            ->useFallbackPath(public_path('/img/default_product.png'));
    }

    public function images()
    {
        return $this->hasOne('Spatie\MediaLibrary\Models\Media', 'model_id')
            ->where('model_type', 'App\Models\UserProfiles');
    }

    public function imagesWithCollection($collection = 'default')
    {
        return $this->hasOne('Spatie\MediaLibrary\Models\Media', 'model_id')
            ->where('model_type', 'App\Models\UserProfiles')
            ->where('collection_name', $collection);
    }

    public function getImage($id)
    {
        return $this->hasOne('Spatie\MediaLibrary\Models\Media', 'model_id')
            ->where('model_type', 'App\Models\UserProfiles')
            ->where('model_id', $id);
    }


}

app/Http/Controllers/UserProfilesController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\UnpaidUserProfilesDataTable;
use App\DataTables\UserProfilesDataTable;
use App\Events\AfterRegister;
use App\Http\Requests;
use App\Http\Requests\CreateUserProfilesRequest;
use App\Http\Requests\UpdateUserProfilesRequest;
use App\Models\UserProfiles;
use App\Repositories\UserProfilesRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Illuminate\Support\Composer;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;
use Response;
use Paystack;
use Zipper;
use App\Paystack\Paystack as PayStackHack;
use Spatie\MediaLibrary\Models\Media;

class UserProfilesController extends AppBaseController
{
    /** @var  UserProfilesRepository */
    private $userProfilesRepository;
    protected $composer;

    public function __construct(UserProfilesRepository $userProfilesRepo, Composer $composer)
    {
        $this->userProfilesRepository = $userProfilesRepo;
        $this->composer = $composer;
        $this->middleware('auth')->except(['register', 'store', 'terms', 'getCount', 'signup', 'thanks']);
    }

    /**
     * Display a listing of the UserProfiles.
     *
     * @param UserProfilesDataTable $userProfilesDataTable
     * @return Response
     */
    public function index(UserProfilesDataTable $userProfilesDataTable)
    {
        $male = UserProfiles::whereHas('payments')->where('sex', 'Male')->count();
        $female = UserProfiles::whereHas('payments')->where('sex', 'Female')->count();
        return $userProfilesDataTable->render('user_profiles.index', compact('male', 'female'));
    }

    /**
     * Display a listing of the UserProfiles.
     *
     * @param UserProfilesDataTable $userProfilesDataTable
     * @return Response
     */
    public function unpaid(UnpaidUserProfilesDataTable $userProfilesDataTable)
    {
        $male = UserProfiles::whereDoesntHave('payments')->where('sex', 'Male')->count();
        $female = UserProfiles::whereDoesntHave('payments')->where('sex', 'Female')->count();
        return $userProfilesDataTable->render('user_profiles.index', compact('male', 'female'));
    }


    public function getCount()
    {
        //Artisan::call('cache:clear');
        // dd(request()->all());
        //return response()->json(['type' => false]);
        $gender = request()->all()['gender'];

        if ($gender == 'Male') {
            $male = getValue('Male');
            $count = UserProfiles::whereHas('payments')->where('sex', 'Male')->count();
            if ($count >= $male) {
                return response()->json(['type' => false]);
            }
            return response()->json(['type' => true]);
        } else if ($gender == 'Female') {
            $female = getValue('Female');
            $count = UserProfiles::whereHas('payments')->where('sex', 'Female')->count();
            if ($count >= $female) {
                return response()->json(['type' => false]);
            }
            return response()->json(['type' => true]);
        }
        return response()->json(['type' => false]);
    }

    /**
     * Show the form for creating a new UserProfiles.
     *
     * @return Response
     */
    public function create()
    {
        return view('user_profiles.create');
    }


    public function terms()
    {
        return view('user_profiles.terms');
    }

    public function thanks()
    {
        return view('user_profiles.thanks');
    }

    public function signup()
    {

        $titles = config('constants.titles');
        $marital = config('constants.marital');
        return view('user_profiles.reg')->with(compact('titles', 'marital'));
    }


    function clean($string)
    {
        $string = str_replace(' ', '-', $string); // Replaces all spaces with hyphens.
        return preg_replace('/[^A-Za-z0-9\-]/', '', $string); // Removes special chars.
    }

    public function download_images()
    {


        try {
            //$this->composer->dumpAutoloads();
            $profiles = UserProfiles::whereHas('payments')->get();

            $appURL = config('app.url') . "/";
            $zipper = new \App\Zipper\Zipper;
            $zipper->make(storage_path('app/paidUsers.zip'));
            foreach ($profiles as $eachProfiles) {
                try {
                    if (!empty($eachProfiles->passport)) {
                        $filez = str_replace('http://localhost/', "", $eachProfiles->passport);
                        $file2 = str_replace($appURL, "", $filez);
                        $exists = File::exists($file2);
                        if ($exists) {
                            $name = $this->clean(@$eachProfiles->full_name);
                            $fullFiles = public_path($file2);
                            $zipper->add($fullFiles, $name);
                        }
                    }
                } catch (\Exception $exception) {
                    dd($exception->getMessage() . " " . $exception->getLine());
                }
            }
            if (empty($zipper->listFiles())) {
                flash()->error("No Files to download");
                return redirect()->back();
            }
            $zipper->close();
        } catch (\Exception $exception) {
            dd($exception->getMessage() . " " . $exception->getLine());
        }

        return response()->download(storage_path('app/paidUsers.zip'))->deleteFileAfterSend();
    }


    public function register()
    {
        //$up = UserProfiles::find(1);
        // event(new AfterRegister($up));
        //flash()->error("Maximum Number of Females Allowed");


        $titles = config('constants.titles');
        $marital = config('constants.marital');
        return view('user_profiles.create')->with(compact('titles', 'marital'));
    }


    /**
     * Store a newly created UserProfiles in storage.
     *
     * @param CreateUserProfilesRequest $request
     *
     * @return Response
     */
    public function store()
    {

        //dd($input);
        //CreateUserProfilesRequest $request
        ini_set('post_max_size', '120M');
        ini_set('upload_max_filesize', '120M');
        ini_set('memory_limit', '8G');

        $input = request()->all();
        //dd($request->all());
        //$input = $request->all();
        //dd($input = request()->all());
        $input['dob'] = $input['birth_date'] . "-" . $input['birth_month'] . "-" . $input['birth_year'];
        if ($input['sex'] == 'Male') {
            $male = getValue('Male');
            $count = UserProfiles::whereHas('payments')->where('sex', 'Male')->count();
            if ($count >= $male) {
                flash()->error("Maximum Number of Males Allowed");
                return redirect()->back();
            }
        } else if ($input['sex'] == 'Female') {
            $female = getValue('Female');
            $count = UserProfiles::whereHas('payments')->where('sex', 'Female')->count();
            if ($count >= $female) {
                flash()->error("Maximum Number of Females Allowed");
                return redirect()->back();
            }
        }


        $userProfiles = $this->userProfilesRepository->create($input);
        if (!empty(request()->file('passport'))) {
            try {
                $userProfiles->addMedia(request()->file('passport'))
                    ->usingName('Passport')
                    ->toMediaCollection('passport');
                $mediaItems = $userProfiles->getMedia('passport');
                $data['passport'] = $mediaItems[0]->getFullUrl();
                UserProfiles::whereId($userProfiles->id)->update($data);
            } catch (\Exception $exception) {
                flash()->error($exception->getMessage());
                return redirect()->back();
            }
        }


        $id = sprintf("%'03d", $userProfiles->id);
        $paymentRef = "LEMUITIF-2020-" . $id;
        if (config('app.env') == 'local') {
            $paymentRef = Paystack::genTranxRef();
        }

        request()->files->remove('passport');
        //dd($request->files);
        $payment = [
            "amount" => getValue('Amount') * 100,
            // "reference" => Paystack::genTranxRef(),
            "reference" => $paymentRef,
            "email" => $input['email'],
            "first_name" => $input['first_name'],
            "callback_url" => url('payment/callback'),
            "last_name" => $input['last_name'],
        ];

        $data['reference'] = $paymentRef;
        UserProfiles::whereId($userProfiles->id)->update($data);


        request()->merge($payment);
        $ps = new PayStackHack();
        return $ps->getAuthorizationUrl()->redirectNow();

//        Flash::success('You have been successfully Registered');
//        return redirect()->back();
    }

    /**
     * Display the specified UserProfiles.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $logo = '';
        $media = Media::
        where('model_type', 'App\Models\UserProfiles')
            ->where('model_id', $id)
            ->where('name', 'Passport')
            ->first();

        if (!empty($media)) {
            //$logo = $media->getFullUrl('my-conversion');
            $logo = $media->getFullUrl();
        }

        //dd($logo);


        $userProfiles = UserProfiles::with('payments')->where('id', $id)->first();

        // $userProfiles = $this->userProfilesRepository->find($id)->with('payments')->get();


        // dd($userProfiles);
        if (empty($userProfiles)) {
            Flash::error('User Profiles not found');

            return redirect(route('userProfiles.index'));
        }

        return view('user_profiles.show')->with('userProfiles', $userProfiles)->with(compact('logo'));
    }

    /**
     * Show the form for editing the specified UserProfiles.
     *
     * @param  int $id
     *
     * @return Response
     */

resources/views/user_profiles/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="colorlib.com">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form</title>


    <!-- Google Font -->
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Tangerine">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="shortcut icon" href="{{asset("img/logo.png")}}">

    <!-- Font Icon -->
    {{--<link rel="stylesheet" href="{{asset('css/bootstrap.css')}}">--}}
    {{--<link rel="stylesheet" href="{{asset('fonts/material-icon/css/material-design-iconic-font.min.css')}}">--}}
    <link rel="stylesheet" href="{{asset('vendor/nouislider/nouislider.min.css')}}">

    <!-- Main css -->
    <link rel="stylesheet" href="{{asset('css/style.css')}}">
    <!-- Style by Juhla -->
    <link rel="stylesheet" href="{{asset('css/style2.css')}}">




</head>

<body>

<div class="main">

    <div class="container">

        {{--<div>--}}
            {{--<img src="{{ asset('img/logo.jpeg') }}" style="height: 180px;width: 180px"/>--}}
        {{--</div>--}}
        {!! Form::open(['route' => 'userProfiles.store','enctype'=>"multipart/form-data", 'method'=>"POST",'id'=>"signup-form",'class'=>"signup-form"]) !!}
        <div >



            @include('flash::message')
            <h3>Accept Terms</h3>
            <fieldset>
                <div>
                    <img src="{{ asset('img/logo.jpeg') }}" style="height: 120px;width: 120px"/>
                </div>
                <h2 style="font-size: 26px">Lekki Muslim Ummah - Itikaf 2020 Registration Portal</h2>
                {{--@include('user_profiles.steps.confirm')--}}
                {{--@include('user_profiles.steps.other-info')--}}
                {{--@include('user_profiles.steps.personal-info')--}}
                @include('user_profiles.steps.terms-main')
            </fieldset>

            <h3>Personal Information</h3>
            <fieldset>
                <div>
                    <img src="{{ asset('img/logo.jpeg') }}" style="height: 120px;width: 120px"/>
                </div>
                <h2 style="font-size: 26px">Lekki Muslim Ummah - Itikaf 2020 Registration Portal</h2>
                @include('user_profiles.steps.personal-info')
            </fieldset>

            <h3>Other Information</h3>
            <fieldset>
                <div>
                    <img src="{{ asset('img/logo.jpeg') }}" style="height: 120px;width: 120px"/>
                </div>
                <h2 style="font-size: 26px">Lekki Muslim Ummah - Itikaf 2020 Registration Portal</h2>
                @include('user_profiles.steps.other-info')
            </fieldset>


            <h3>Confirm Your Information</h3>
            <fieldset>
                <div>
                    <img src="{{ asset('img/logo.jpeg') }}" style="height: 120px;width: 120px"/>
                </div>
                <h2 style="font-size: 26px">Lekki Muslim Ummah - Itikaf 2020 Registration Portal</h2>
                @include('user_profiles.steps.confirm')
            </fieldset>
        </div>
        {!! Form::close() !!}
    </div>

</div>

<!-- JS -->

<script src="{{asset('vendor/jquery/jquery.min.js')}}"></script>
<script src="{{asset('vendor/jquery-validation/dist/jquery.validate.min.js')}}"></script>
<script src="{{asset('vendor/jquery-validation/dist/additional-methods.min.js')}}"></script>
<script src="{{asset('vendor/jquery-steps/jquery.steps.min.js')}}"></script>
<script src="{{asset('vendor/minimalist-picker/dobpicker.js')}}"></script>
<script src="{{asset('vendor/nouislider/nouislider.min.js')}}"></script>
<script src="{{asset('vendor/wnumb/wNumb.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js"></script>
<script
    src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>
<script src="{{asset('bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script>
@include('user_profiles.steps.main-reg')
<script>
    $(function () {
        $('.datepicker').datepicker({
            format: 'dd-mm-yyyy',
        });
    })
</script>
</body>

</html>

resources/views/user_profiles/create2.blade.php
@extends('layouts.unauth')

@section('content')
    <span>
						<img src="{{ asset('img/logo.png') }}" alt="" class="wheel-img"
                             style="padding-left: 30px"/>
					</span>
    <div class="container-fluid">
        <div class="animated fadeIn">

            <div class="row">

                <div class="col-lg-8">
                    @include('flash::message')
                    <div class="card">
                        <div class="card-header">
                            <strong><h3>Lekki Muslim Ummah - Itikaf 2020 Registrations</h3></strong>
                        </div>
                        <div class="card-body">
                            {!! Form::open(['route' => 'userProfiles.store','enctype'=>"multipart/form-data",'id'=>"payment_form"]) !!}

                            @include('user_profiles.fields')

                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


@endsection
@section('stylesheet')
    <link rel="stylesheet" href="{{asset('bootstrap-datepicker/css/bootstrap-datepicker3.css')}}">
@endsection
@section('scripts')
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{{asset('bootstrap-datepicker/js/bootstrap-datepicker.js')}}"></script>
    <script>
        $(function () {
            $('.datepicker').datepicker({
                format: 'dd-mm-yyyy',
            });
        })
    </script>
@endsection

resources/views/user_profiles/datatables_actions.blade.php
{!! Form::open(['route' => ['userProfiles.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('userProfiles.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    {{--<a href="{{ route('userProfiles.edit', $id) }}" class='btn btn-ghost-info'>--}}
       {{--<i class="fa fa-edit"></i>--}}
    {{--</a>--}}
    {{--{!! Form::button('<i class="fa fa-trash"></i>', [--}}
        {{--'type' => 'submit',--}}
        {{--'class' => 'btn btn-ghost-danger',--}}
        {{--'onclick' => "return confirm('Are you sure?')"--}}
    {{--]) !!}--}}
</div>
{!! Form::close() !!}

resources/views/user_profiles/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('userProfiles.index') !!}">User Profiles</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit User Profiles</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($userProfiles, ['route' => ['userProfiles.update', $userProfiles->id], 'method' => 'patch']) !!}

                              @include('user_profiles.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/user_profiles/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">User List</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
            @include('flash::message')
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header">
                            <i class="fa fa-align-justify"></i>
                            <span><strong>Male</strong> : {{$male}}</span>,
                            <span><strong>Female</strong> : {{$female}}</span>
                            <a href="{{ url('userProfiles/download_images') }}" class="btn btn-primary">Download Images</a>
                            <a class="pull-right" href="{{ route('userProfiles.create') }}"><i
                                    class="fa fa-plus-square fa-lg"></i></a>
                        </div>
                        <div class="card-body">
                            @include('user_profiles.table')
                            <div class="pull-right mr-3">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/user_profiles/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('userProfiles.index') }}">User Profiles</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('userProfiles.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('user_profiles.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/user_profiles/show_fields.blade.php
<div class="form-group">
    <div class="item active">
        <img src="{{ $logo }}" alt="image" width="300px" height="300px">
    </div>
</div>


<!-- Title Id Field -->
<div class="form-group">
    {!! Form::label('reg', 'Registration Number:') !!}
    <p>{{ @$userProfiles->payments->reference }}</p>
</div>

<!-- Title Id Field -->
<div class="form-group">
    {!! Form::label('title_id', 'Title:') !!}
    <p>{{ $userProfiles->title }}</p>
</div>

<!-- First Name Field -->
<div class="form-group">
    {!! Form::label('first_name', 'First Name:') !!}
    <p>{{ $userProfiles->first_name }}</p>
</div>

<!-- Other Name Field -->
<div class="form-group">
    {!! Form::label('other_name', 'Other Name:') !!}
    <p>{{ $userProfiles->other_name }}</p>
</div>

<!-- Last Name Field -->
<div class="form-group">
    {!! Form::label('last_name', 'Last Name:') !!}
    <p>{{ $userProfiles->last_name }}</p>
</div>

<!-- Sex Field -->
<div class="form-group">
    {!! Form::label('sex', 'Sex:') !!}
    <p>{{ $userProfiles->sex }}</p>
</div>

<!-- Dob Field -->
<div class="form-group">
    {!! Form::label('dob', 'Dob:') !!}
    <p>{{ $userProfiles->dob }}</p>
</div>

<!-- Marital Status Field -->
<div class="form-group">
    {!! Form::label('marital_status', 'Marital Status:') !!}
    <p>{{ $userProfiles->marital_status }}</p>
</div>

<!-- Profession Field -->
<div class="form-group">
    {!! Form::label('profession', 'Profession:') !!}
    <p>{{ $userProfiles->profession }}</p>
</div>

<!-- Employer Field -->
<div class="form-group">
    {!! Form::label('employer', 'Employer:') !!}
    <p>{{ $userProfiles->employer }}</p>
</div>

<!-- Home Address Field -->
<div class="form-group">
    {!! Form::label('home_address', 'Home Address:') !!}
    <p>{{ $userProfiles->home_address }}</p>
</div>

<!-- Office Address Field -->
<div class="form-group">
    {!! Form::label('office_address', 'Office Address:') !!}
    <p>{{ $userProfiles->office_address }}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{{ $userProfiles->email }}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{{ $userProfiles->phone }}</p>
</div>


<div class="form-group">
    {!! Form::label('next_of_kin', 'Next of Kin:') !!}
    <p>{{ $userProfiles->next_of_kin }}</p>
</div>

<div class="form-group">
    {!! Form::label('next_of_kin_phone', 'Next of Kin Phone:') !!}
    <p>{{ $userProfiles->next_of_kin_phone }}</p>
</div>

resources/views/user_profiles/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection

resources/views/user_profiles/unpaid_datatables_actions.blade.php
{!! Form::open(['route' => ['userProfiles.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('userProfiles.show', $id) }}" class='btn btn-ghost-success'>
        <i class="fa fa-eye"></i>
    </a>
    {{--<a href="{{ route('userProfiles.edit', $id) }}" class='btn btn-ghost-info'>--}}
    {{--<i class="fa fa-edit"></i>--}}
    {{--</a>--}}
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}