routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'UserProfilesController@register');
Route::get('thanks', 'UserProfilesController@thanks');
Route::get('/signup', 'UserProfilesController@signup');
Route::get('/terms', 'UserProfilesController@terms');
Route::get('/getCount', 'UserProfilesController@getCount');
Route::post('/create', 'UserProfilesController@create');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');



Route::post('/pay', [
    'uses' => 'PaymentController@redirectToGateway',
    'as' => 'pay'
]);
Route::get('/payment/callback', 'PaymentController@handleGatewayCallback');
Route::get('/payment/webhook', 'PaymentController@handleGatewayWebhook');
Route::get('userProfiles/unpaid', 'UserProfilesController@unpaid');
Route::get('userProfiles/download_images', 'UserProfilesController@download_images');
Route::resource('userProfiles', 'UserProfilesController');

Route::resource('payments', 'PaymentController');


Route::resource('modelSettings', 'ModelSettingsController');

Route::resource('settings', 'SettingsController');

app/Models/ModelSettings.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class ModelSettings
 * @package App\Models
 * @version February 8, 2020, 4:06 pm UTC
 *
 * @property integer model_id
 * @property string model_type
 * @property string settings
 */
class ModelSettings extends Model
{
    //  use SoftDeletes;

    public $table = 'model_settings';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'model_id',
        'model_type',
        'settings'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'model_id' => 'integer',
        'model_type' => 'string',
        'settings' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'model_id' => 'required',
        'model_type' => 'required',
        'settings' => 'required'
    ];

    
}

app/Http/Controllers/ModelSettingsController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\ModelSettingsDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateModelSettingsRequest;
use App\Http\Requests\UpdateModelSettingsRequest;
use App\Repositories\ModelSettingsRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class ModelSettingsController extends AppBaseController
{
    /** @var  ModelSettingsRepository */
    private $modelSettingsRepository;

    public function __construct(ModelSettingsRepository $modelSettingsRepo)
    {
        $this->modelSettingsRepository = $modelSettingsRepo;
    }

    /**
     * Display a listing of the ModelSettings.
     *
     * @param ModelSettingsDataTable $modelSettingsDataTable
     * @return Response
     */
    public function index(ModelSettingsDataTable $modelSettingsDataTable)
    {
        return $modelSettingsDataTable->render('model_settings.index');
    }

    /**
     * Show the form for creating a new ModelSettings.
     *
     * @return Response
     */
    public function create()
    {
        return view('model_settings.create');
    }

    /**
     * Store a newly created ModelSettings in storage.
     *
     * @param CreateModelSettingsRequest $request
     *
     * @return Response
     */
    public function store(CreateModelSettingsRequest $request)
    {
        $input = $request->all();

        $modelSettings = $this->modelSettingsRepository->create($input);

        Flash::success('Model Settings saved successfully.');

        return redirect(route('modelSettings.index'));
    }

    /**
     * Display the specified ModelSettings.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $modelSettings = $this->modelSettingsRepository->find($id);

        if (empty($modelSettings)) {
            Flash::error('Model Settings not found');

            return redirect(route('modelSettings.index'));
        }

        return view('model_settings.show')->with('modelSettings', $modelSettings);
    }

    /**
     * Show the form for editing the specified ModelSettings.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $modelSettings = $this->modelSettingsRepository->find($id);

        if (empty($modelSettings)) {
            Flash::error('Model Settings not found');

            return redirect(route('modelSettings.index'));
        }

        return view('model_settings.edit')->with('modelSettings', $modelSettings);
    }

    /**
     * Update the specified ModelSettings in storage.
     *
     * @param  int              $id
     * @param UpdateModelSettingsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateModelSettingsRequest $request)
    {
        $modelSettings = $this->modelSettingsRepository->find($id);

        if (empty($modelSettings)) {
            Flash::error('Model Settings not found');

            return redirect(route('modelSettings.index'));
        }

        $modelSettings = $this->modelSettingsRepository->update($request->all(), $id);

        Flash::success('Model Settings updated successfully.');

        return redirect(route('modelSettings.index'));
    }

    /**
     * Remove the specified ModelSettings from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $modelSettings = $this->modelSettingsRepository->find($id);

        if (empty($modelSettings)) {
            Flash::error('Model Settings not found');

            return redirect(route('modelSettings.index'));
        }

        $this->modelSettingsRepository->delete($id);

        Flash::success('Model Settings deleted successfully.');

        return redirect(route('modelSettings.index'));
    }
}

resources/views/model_settings/create.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
         <a href="{!! route('modelSettings.index') !!}">Model Settings</a>
      </li>
      <li class="breadcrumb-item active">Create</li>
    </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                @include('coreui-templates::common.errors')
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-header">
                                <i class="fa fa-plus-square-o fa-lg"></i>
                                <strong>Create Model Settings</strong>
                            </div>
                            <div class="card-body">
                                {!! Form::open(['route' => 'modelSettings.store']) !!}

                                   @include('model_settings.fields')

                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
           </div>
    </div>
@endsection

resources/views/model_settings/datatables_actions.blade.php
{!! Form::open(['route' => ['modelSettings.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('modelSettings.show', $id) }}" class='btn btn-ghost-success'>
       <i class="fa fa-eye"></i>
    </a>
    <a href="{{ route('modelSettings.edit', $id) }}" class='btn btn-ghost-info'>
       <i class="fa fa-edit"></i>
    </a>
    {!! Form::button('<i class="fa fa-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-ghost-danger',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/model_settings/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('modelSettings.index') !!}">Model Settings</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Model Settings</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($modelSettings, ['route' => ['modelSettings.update', $modelSettings->id], 'method' => 'patch']) !!}

                              @include('model_settings.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/model_settings/fields.blade.php
<!-- Model Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('key', 'Key:') !!}
    {!! Form::number('key', null, ['class' => 'form-control','required'=>'required']) !!}
</div>

<!-- Model Type Field -->
<div class="form-group col-sm-6">
    {!! Form::label('value', 'Value:') !!}
    {!! Form::text('value', null, ['class' => 'form-control','required'=>'required']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('modelSettings.index') }}" class="btn btn-secondary">Cancel</a>
</div>

resources/views/model_settings/index.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">Model Settings</li>
    </ol>
    <div class="container-fluid">
        <div class="animated fadeIn">
             @include('flash::message')
             <div class="row">
                 <div class="col-lg-12">
                     <div class="card">
                         <div class="card-header">
                             <i class="fa fa-align-justify"></i>
                             ModelSettings
                             <a class="pull-right" href="{{ route('modelSettings.create') }}"><i class="fa fa-plus-square fa-lg"></i></a>
                         </div>
                         <div class="card-body">
                             @include('model_settings.table')
                              <div class="pull-right mr-3">
                                     
                              </div>
                         </div>
                     </div>
                  </div>
             </div>
         </div>
    </div>
@endsection

resources/views/model_settings/show.blade.php
@extends('layouts.app')

@section('content')
     <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('modelSettings.index') }}">Model Settings</a>
            </li>
            <li class="breadcrumb-item active">Detail</li>
     </ol>
     <div class="container-fluid">
          <div class="animated fadeIn">
                 @include('coreui-templates::common.errors')
                 <div class="row">
                     <div class="col-lg-12">
                         <div class="card">
                             <div class="card-header">
                                 <strong>Details</strong>
                                  <a href="{{ route('modelSettings.index') }}" class="btn btn-light">Back</a>
                             </div>
                             <div class="card-body">
                                 @include('model_settings.show_fields')
                             </div>
                         </div>
                     </div>
                 </div>
          </div>
    </div>
@endsection

resources/views/model_settings/show_fields.blade.php
<!-- Model Id Field -->
<div class="form-group">
    {!! Form::label('model_id', 'Model Id:') !!}
    <p>{{ $modelSettings->model_id }}</p>
</div>

<!-- Model Type Field -->
<div class="form-group">
    {!! Form::label('model_type', 'Model Type:') !!}
    <p>{{ $modelSettings->model_type }}</p>
</div>

<!-- Settings Field -->
<div class="form-group">
    {!! Form::label('settings', 'Settings:') !!}
    <p>{{ $modelSettings->settings }}</p>
</div>

resources/views/model_settings/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endsection